<div style="padding-top: 100px">
    <div style="text-align: center;font-weight: bold;text-decoration: underline;padding-right: 1150px">MAKE WITH RECYCLED MATERIALS</div>
    <div style="text-align: center;font-size: 35px"><h2>THREE PATHS SHAPING ADIDAS’ FUTURE TO HELP END PLASTIC WASTE</h2>
    </div>
    <div style="text-align: center"><i>April 15, 2021</i></div>
</div>
<div>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/1920x1080/583036_v2.jpg" style="width: 65%;padding: 40px;float: left;clear: both"/>
</div>
<div style="padding: 40px;text-align: center;font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif';text-decoration: underline">
    <p><h3>WE ARE IN HURRY</h3></p>
</div>
<div style="padding: 15px;text-align: center">
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/320x320/582933.jpg" style="width: 15%;height: 215px"/>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/320x320/582862.jpg" style="width: 15%;height: 215px"/>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/320x320/582863.jpg" style="width: 15%;height: 215px"/>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/400x300/582931.jpg" style="width: 15%;height: 215px"/>
</div>
<div style="font-size: 20px">
    <p style="width: 65%;padding:40px;text-indent: 50px">Could changing the materials we use in sport make ending plastic waste a possibility? We believe that it can help accelerate towards that goal. We have a twenty-year track record of working towards sustainability and more recently have doubled down on a journey to seek out better solutions for high-performance materials that have minimal environmental compromise. </p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">Our idea is to help End Plastic Waste by developing products that either: use recycled materials, are made to be remade, or are made with nature. We’re forging new ways forward in each of these lanes, working with a team of collaborators from our industry and beyond, setting the pace for the industry at-large.  </p>
    <p style="padding: 10px 40px;font-weight: bold">Material Innovations</p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">When we say made with recycled materials we are speaking to our products that are made in part with recycled polyester or Parley Ocean Plastic - upcycled plastic waste intercepted on beaches and coastal communities, preventing it from polluting the oceans. Since 2015, we’ve created more than 30 million pairs of shoes with Parley Ocean Plastic, half of which were produced last year alone. </p>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/640x480/582934.jpg" style="width: 50%;margin: 80px"/>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">We’re taking on a series of new missions with Parley over the next few months to protect the earth’s water systems, from oceans to mountains to rivers. Each will aim to educate on the effect of plastic pollution and hopefully inspire people to take action, whilst keeping us focused on designing solutions. </p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">Similar to how our journey started with Parley for the Oceans, sharing a single prototype with the world, we’ll soon unveil two new Parley prototypes. The first features a midsole that’s made in part with recycled post-production Boost material, and the second’s upper contains wood waste - it sits on another Boost midsole concept partially made with plant-based feedstocks. Both were created with new exploratory design processes as we continue to find more sustainable possibilities and alternatives for virgin polyester.  </p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">They kick off upcoming new Ultraboost drops, with new Ultraboost 21 x Parley and Ultraboost DNA x Parley running shoes made with reclaimed fishing nets launching over the coming weeks.   </p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">‘Made to be remade’ is product that’s made to be worn, returned to us, ground up and remade into something new. After three generations of prototypes, we’ll be dropping the first Ultraboost DNA Made to Be Remade, made from 100% TPU, on Earth Day April 22. We’ll also be rolling out a new takeback experience over the coming months - once your UB MTBR is worn out, you’ll be able to scan the on-shoe QR code or open the adidas app to start the return process and then we will guide you through the steps to return your product back to us. </p>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/640x480/582933.jpg" style="width: 50%;margin: 80px"/>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px"> Earlier this month we finished beta testing our Terrex “FUTURECRAFT.LOOP Anorak concept” with 50 creators worldwide. It’s a performance jacket prototype that’s designed to be returned and remodelled into new apparel - we’re targeting a wider release in 2022.  </p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px"> This is just the start. We’re also building new ways to keep products in play for longer through our Infinite Play program. It will include product takeback, resale, rental and subscription services. We’ll launch a takeback program in the US later this year and we’ll also be trialling a rental program for Terrex products this coming season in France.  </p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">Products that are ‘made with nature’ are sport and streetwear made in part with natural and renewable materials - offering additional innovative options that are created responsibly with inputs based on renewable resources. Today we’re sharing our first footwear created with the underground roots of mushrooms: Stan Smith Mylo.</p>
    <p style="width: 65%;padding:10px 40px;text-indent: 50px">Our approach to innovation has always been about collaborating with partners, experts and occasionally competitors that can push us and our industry forward. Stan Smith Mylo is the result of a collaboration with our long-time partner Bolt Threads - a biotechnology company committed to creating the next generation of advanced materials. </p>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/640x480/582863.jpg" style="width: 50%;margin: 80px"/>
    <p style="width: 65%;padding: 10px 40px;text-indent: 50px">Mylo is a soft, supple and strong material. It’s made with renewable Mycelium, which is created using a grow process that takes less than two weeks and uses a cutting-edge vertical agriculture technique, allowing it to be grown in a controlled lab environment that increases the yield per square foot. </p>
    <p style="width: 65%;padding: 10px 40px;text-indent: 50px">We’re incredibly excited about Mylo and the material innovation and creation possibilities it represents. It is a versatile material that can take any colour, finish or emboss, but we chose the classic Stan Smith as the first adidas shoe to be transformed by Mylo, building on its creds as one of adidas’ most iconic and sustainable footwear franchises.</p>
    <p style="padding: 10px 40px;font-weight: bold">Joining The Mission to Help End Plastic Waste  </p>
    <p style="width: 65%;padding: 40px;text-indent: 50px">Alongside new concepts and products, our next mission with Parley starts ahead of World Oceans Day (June 8), where we will harness the power of sport as a force for change, inviting everyone to “Run For The Oceans” once again. Since 2017, the initiative has united over 3 million runners around the world, collectively clocking up 25.5 million kms and raising $2.5 million to help Parley develop several initiatives and educational programs in the fight against marine plastic pollution.  </p>
    <img src="https://preview.thenewsmarket.com/Previews/ADID/StillAssets/640x480/582932.gif" style="width: 50%;margin: 60px"/>
    <p style="width: 65%;padding: 10px;text-indent: 50px;margin-bottom: 80px">Empowering runners worldwide to make a difference, for every kilometre run between May 28 and June 8 via the adidas Running app, Parley global clean up network will clean up the equivalent weight of 10 plastic bottles, up to a maximum of 500,000 lbs of marine plastic waste from beaches, remote islands, and coastlines. There’s more to come in May on how you can get involved - in the meantime drop by adidas.com/runfortheoceans and follow #RFTO on Twitter or Instagram for all the latest as it happens.</p>
</div>